name: flowers102
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - pip:
      - timm
